### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by CarlFK** [evezor/EdgeIDE#19]
each board gets a color. the lines coming out from a board get the board's color.

this would help with lines overlapping.  If only 1 red goes in and out of a overlap, it is clear what the red line does.

**Comment by anfroholic** [comment]
I had a similar thought to this especially with regards to operators so it's easy to tell which device that specific operator is running on.

**Comment by jcmertz** [comment]
Board colors are taken care of in commit [e64bf37](https://github.com/evezor/EdgeIDE/commit/e64bf37fd37b6f3c71301c0b7d3793bcbbfb7899)

Connection colors are harder, as connections don't have an "owner" they are an entity that exists connecting two figures but don't exist as a child of either figure, AFAIK. 

I'm closing this for now, as I think the different line types and the ability to select lines helps solve this problem. If anyone feels different feel free to reopen.
